import type { Product, Collection } from "@/lib/shopify/types";

export const collections: Collection[] = [
  {
    handle: "wedding",
    title: "Wedding Invitations",
    description: "Elegant wedding invites",
    seo: {
      title: "Wedding Invitations",
      description: "Elegant wedding invites",
    },
    parentCategoryTree: [],
    updatedAt: new Date().toISOString(),
    path: "/categories/wedding",
  },
  {
    handle: "birthday",
    title: "Birthday Invitations",
    description: "Fun birthday party invites",
    seo: {
      title: "Birthday Invitations",
      description: "Fun birthday party invites",
    },
    parentCategoryTree: [],
    updatedAt: new Date().toISOString(),
    path: "/categories/birthday",
  },
  {
    handle: "events",
    title: "Event Invitations",
    description: "Party hard and special event invites",
    seo: {
      title: "Event Invitations",
      description: "Party hard and special event invites",
    },
    parentCategoryTree: [],
    updatedAt: new Date().toISOString(),
    path: "/categories/events",
  },
];

export const products: Product[] = [
  {
    id: "wedding-1",
    title: "Classic Wedding",
    handle: "classic-wedding",
    description: "A timeless and elegant wedding invitation design.",
    descriptionHtml: "<p>A timeless and elegant wedding invitation design.</p>",
    categoryId: "wedding",
    featuredImage: {
      url: "/templates/weddings/wedding-inv-1.png",
      altText: "Classic Wedding",
      width: 800,
      height: 600,
    },
    currencyCode: "USD",
    priceRange: {
      minVariantPrice: { amount: "29.99", currencyCode: "USD" },
      maxVariantPrice: { amount: "29.99", currencyCode: "USD" },
    },
    seo: { title: "Classic Wedding", description: "Elegant wedding invitation" },
    options: [],
    tags: ["wedding"],
    variants: [],
    images: [
      {
        url: "/templates/weddings/wedding-inv-1.png",
        altText: "Classic Wedding",
        width: 800,
        height: 600,
      },
    ],
    availableForSale: true,
  },
  {
    id: "wedding-2",
    title: "Modern Wedding",
    handle: "modern-wedding",
    description: "Minimalist and modern wedding style.",
    descriptionHtml: "<p>Minimalist and modern wedding style.</p>",
    categoryId: "wedding",
    featuredImage: {
      url: "/templates/weddings/wedding-inv-2.png",
      altText: "Modern Wedding",
      width: 800,
      height: 600,
    },
    currencyCode: "USD",
    priceRange: {
      minVariantPrice: { amount: "34.99", currencyCode: "USD" },
      maxVariantPrice: { amount: "34.99", currencyCode: "USD" },
    },
    seo: { title: "Modern Wedding", description: "Modern wedding invite" },
    options: [],
    tags: ["wedding"],
    variants: [],
    images: [
      {
        url: "/templates/weddings/wedding-inv-2.png",
        altText: "Modern Wedding",
        width: 800,
        height: 600,
      },
    ],
    availableForSale: true,
  },
  {
    id: "wedding-3",
    title: "Luxury Wedding",
    handle: "luxury-wedding",
    description: "Premium luxury design with gold elements.",
    descriptionHtml: "<p>Premium luxury design with gold elements.</p>",
    categoryId: "wedding",
    featuredImage: {
      url: "/templates/weddings/wedding-inv-3.png",
      altText: "Luxury Wedding",
      width: 800,
      height: 600,
    },
    currencyCode: "USD",
    priceRange: {
      minVariantPrice: { amount: "39.99", currencyCode: "USD" },
      maxVariantPrice: { amount: "39.99", currencyCode: "USD" },
    },
    seo: { title: "Luxury Wedding", description: "Luxury style wedding invite" },
    options: [],
    tags: ["wedding"],
    variants: [],
    images: [
      {
        url: "/templates/weddings/wedding-inv-3.png",
        altText: "Luxury Wedding",
        width: 800,
        height: 600,
      },
    ],
    availableForSale: true,
  },

  // Birthday
  {
    id: "birthday-1",
    title: "Fun Birthday",
    handle: "fun-birthday",
    description: "Bright and colorful fun birthday template.",
    descriptionHtml: "<p>Bright and colorful fun birthday template.</p>",
    categoryId: "birthday",
    featuredImage: {
      url: "/templates/birthdays/birthday-inv-1.png",
      altText: "Fun Birthday",
      width: 800,
      height: 600,
    },
    currencyCode: "USD",
    priceRange: {
      minVariantPrice: { amount: "19.99", currencyCode: "USD" },
      maxVariantPrice: { amount: "19.99", currencyCode: "USD" },
    },
    seo: { title: "Fun Birthday", description: "Fun birthday invite" },
    options: [],
    tags: ["birthday"],
    variants: [],
    images: [
      {
        url: "/templates/birthdays/birthday-inv-1.png",
        altText: "Fun Birthday",
        width: 800,
        height: 600,
      },
    ],
    availableForSale: true,
  },
  {
    id: "birthday-2",
    title: "Kids Birthday",
    handle: "kids-birthday",
    description: "Cute and playful invite for kids' birthdays.",
    descriptionHtml: "<p>Cute and playful invite for kids' birthdays.</p>",
    categoryId: "birthday",
    featuredImage: {
      url: "/templates/birthdays/birthday-inv-2.png",
      altText: "Kids Birthday",
      width: 800,
      height: 600,
    },
    currencyCode: "USD",
    priceRange: {
      minVariantPrice: { amount: "17.99", currencyCode: "USD" },
      maxVariantPrice: { amount: "17.99", currencyCode: "USD" },
    },
    seo: { title: "Kids Birthday", description: "Kids birthday invite" },
    options: [],
    tags: ["birthday"],
    variants: [],
    images: [
      {
        url: "/templates/birthdays/birthday-inv-2.png",
        altText: "Kids Birthday",
        width: 800,
        height: 600,
      },
    ],
    availableForSale: true,
  },
  {
    id: "birthday-3",
    title: "Birthday Bash",
    handle: "birthday-bash",
    description: "Perfect for milestone birthday parties.",
    descriptionHtml: "<p>Perfect for milestone birthday parties.</p>",
    categoryId: "birthday",
    featuredImage: {
      url: "/templates/birthdays/birthday-inv-1.png",
      altText: "Birthday Bash",
      width: 800,
      height: 600,
    },
    currencyCode: "USD",
    priceRange: {
      minVariantPrice: { amount: "24.99", currencyCode: "USD" },
      maxVariantPrice: { amount: "24.99", currencyCode: "USD" },
    },
    seo: { title: "Birthday Bash", description: "Birthday party invite" },
    options: [],
    tags: ["birthday"],
    variants: [],
    images: [
      {
        url: "/templates/birthdays/birthday-inv-1.png",
        altText: "Birthday Bash",
        width: 800,
        height: 600,
      },
    ],
    availableForSale: true,
  },

  // Events
  {
    id: "events-1",
    title: "Bachelor Night",
    handle: "bachelor-night",
    description: "Bachelor party themed template.",
    descriptionHtml: "<p>Bachelor party themed template.</p>",
    categoryId: "events",
    featuredImage: {
      url: "/templates/events/event-inv-1.png",
      altText: "Bachelor Night",
      width: 800,
      height: 600,
    },
    currencyCode: "USD",
    priceRange: {
      minVariantPrice: { amount: "25.99", currencyCode: "USD" },
      maxVariantPrice: { amount: "25.99", currencyCode: "USD" },
    },
    seo: { title: "Bachelor Night", description: "Bachelor party invite" },
    options: [],
    tags: ["events"],
    variants: [],
    images: [
      {
        url: "/templates/events/event-inv-1.png",
        altText: "Bachelor Night",
        width: 800,
        height: 600,
      },
    ],
    availableForSale: true,
  },
  {
    id: "events-2",
    title: "Corporate Event",
    handle: "corporate-event",
    description: "Professional design for business events.",
    descriptionHtml: "<p>Professional design for business events.</p>",
    categoryId: "events",
    featuredImage: {
      url: "/templates/events/event-inv-1.png",
      altText: "Corporate Event",
      width: 800,
      height: 600,
    },
    currencyCode: "USD",
    priceRange: {
      minVariantPrice: { amount: "29.99", currencyCode: "USD" },
      maxVariantPrice: { amount: "29.99", currencyCode: "USD" },
    },
    seo: { title: "Corporate Event", description: "Corporate event invite" },
    options: [],
    tags: ["events"],
    variants: [],
    images: [
      {
        url: "/templates/events/event-inv-1.png",
        altText: "Corporate Event",
        width: 800,
        height: 600,
      },
    ],
    availableForSale: true,
  },
  {
    id: "events-3",
    title: "Summer Party",
    handle: "summer-party",
    description: "Vibrant summer party invitation.",
    descriptionHtml: "<p>Vibrant summer party invitation.</p>",
    categoryId: "events",
    featuredImage: {
      url: "/templates/events/event-inv-1.png",
      altText: "Summer Party",
      width: 800,
      height: 600,
    },
    currencyCode: "USD",
    priceRange: {
      minVariantPrice: { amount: "21.99", currencyCode: "USD" },
      maxVariantPrice: { amount: "21.99", currencyCode: "USD" },
    },
    seo: { title: "Summer Party", description: "Summer party invite" },
    options: [],
    tags: ["events"],
    variants: [],
    images: [
      {
        url: "/templates/events/event-inv-1.png",
        altText: "Summer Party",
        width: 800,
        height: 600,
      },
    ],
    availableForSale: true,
  },
];
