import type { Product, Collection } from "@/lib/shopify/types";

export const collections: Collection[] = [
  {
    handle: "wedding",
    title: "Wedding Invitations",
    description: "Elegant wedding invites",
    seo: {
      title: "Wedding Invitations",
      description: "Elegant wedding invites",
    },
    parentCategoryTree: [],
    updatedAt: new Date().toISOString(),
    path: "/categories/wedding",
  },
  {
    handle: "birthday",
    title: "Birthday Invitations",
    description: "Fun birthday party invites",
    seo: {
      title: "Birthday Invitations",
      description: "Fun birthday party invites",
    },
    parentCategoryTree: [],
    updatedAt: new Date().toISOString(),
    path: "/categories/birthday",
  },
  {
    handle: "events",
    title: "Event Invitations",
    description: "Party hard and special event invites",
    seo: {
      title: "Event Invitations",
      description: "Party hard and special event invites",
    },
    parentCategoryTree: [],
    updatedAt: new Date().toISOString(),
    path: "/categories/events",
  },
];

export const products: Product[] = [
  // -----------------------------
  // WEDDING (min 50, step 50)
  // -----------------------------
  {
    id: 1,
    title: "Classic Wedding",
    handle: "classic-wedding",
    description:
      "A timeless and elegant wedding invitation design that exudes sophistication and grace.",
    descriptionHtml: "<p>A timeless and elegant wedding invitation design.</p>",
    categoryId: "wedding",
    compareAtPrice: { amount: "1.00", currencyCode: "EUR" },
    featuredImage: {
      url: "/templates/weddings/wedding-inv-1.png",
      altText: "Classic Wedding",
      width: 800,
      height: 600,
    },
    currencyCode: "EUR",
    priceRange: {
      minVariantPrice: { amount: "0.75", currencyCode: "EUR" },
      maxVariantPrice: { amount: "0.75", currencyCode: "EUR" },
    },
    seo: { title: "Classic Wedding", description: "Elegant wedding invitation" },
    options: [],
    tags: ["wedding"],
    variants: [],
    images: [
      {
        url: "/templates/weddings/wedding-inv-1.png",
        altText: "Classic Wedding",
        width: 800,
        height: 600,
      },
    ],
    availableForSale: true,
    minQuantity: 50,
    quantityStep: 50,
  },
  {
    id: 2,
    title: "Modern Wedding",
    handle: "modern-wedding",
    description: "Minimalist and modern wedding style.",
    descriptionHtml: "<p>Minimalist and modern wedding style.</p>",
    categoryId: "wedding",
    compareAtPrice: { amount: "1.00", currencyCode: "EUR" },
    featuredImage: {
      url: "/templates/weddings/wedding-inv-2.png",
      altText: "Modern Wedding",
      width: 800,
      height: 600,
    },
    currencyCode: "EUR",
    priceRange: {
      minVariantPrice: { amount: "0.75", currencyCode: "EUR" },
      maxVariantPrice: { amount: "0.75", currencyCode: "EUR" },
    },
    seo: { title: "Modern Wedding", description: "Modern wedding invite" },
    options: [],
    tags: ["wedding"],
    variants: [],
    images: [
      {
        url: "/templates/weddings/wedding-inv-2.png",
        altText: "Modern Wedding",
        width: 800,
        height: 600,
      },
    ],
    availableForSale: true,
    minQuantity: 50,
    quantityStep: 50,
  },
  {
    id: 3,
    title: "Luxury Wedding",
    handle: "luxury-wedding",
    description: "Premium luxury design with gold elements.",
    descriptionHtml: "<p>Premium luxury design with gold elements.</p>",
    categoryId: "wedding",
    compareAtPrice: { amount: "1.00", currencyCode: "EUR" },
    featuredImage: {
      url: "/templates/weddings/wedding-inv-3.png",
      altText: "Luxury Wedding",
      width: 800,
      height: 600,
    },
    currencyCode: "EUR",
    priceRange: {
      minVariantPrice: { amount: "0.75", currencyCode: "EUR" },
      maxVariantPrice: { amount: "0.75", currencyCode: "EUR" },
    },
    seo: { title: "Luxury Wedding", description: "Luxury style wedding invite" },
    options: [],
    tags: ["wedding"],
    variants: [],
    images: [
      {
        url: "/templates/weddings/wedding-inv-3.png",
        altText: "Luxury Wedding",
        width: 800,
        height: 600,
      },
    ],
    availableForSale: true,
    minQuantity: 50,
    quantityStep: 50,
  },

  // -----------------------------
  // BIRTHDAY (min 30, step 20)
  // -----------------------------
  {
    id: 4,
    title: "Fun Birthday",
    handle: "fun-birthday",
    description: "Bright and colorful fun birthday template.",
    descriptionHtml: "<p>Bright and colorful fun birthday template.</p>",
    categoryId: "birthday",
    compareAtPrice: { amount: "1.00", currencyCode: "EUR" },
    featuredImage: {
      url: "/templates/birthdays/birthday-inv-1.png",
      altText: "Fun Birthday",
      width: 800,
      height: 600,
    },
    currencyCode: "EUR",
    priceRange: {
      minVariantPrice: { amount: "0.75", currencyCode: "EUR" },
      maxVariantPrice: { amount: "0.75", currencyCode: "EUR" },
    },
    seo: { title: "Fun Birthday", description: "Fun birthday invite" },
    options: [],
    tags: ["birthday"],
    variants: [],
    images: [
      {
        url: "/templates/birthdays/birthday-inv-1.png",
        altText: "Fun Birthday",
        width: 800,
        height: 600,
      },
    ],
    availableForSale: true,
    minQuantity: 30,
    quantityStep: 20,
  },
  {
    id: 5,
    title: "Kids Birthday",
    handle: "kids-birthday",
    description: "Cute and playful invite for kids' birthdays.",
    descriptionHtml: "<p>Cute and playful invite for kids' birthdays.</p>",
    categoryId: "birthday",
    compareAtPrice: { amount: "1.00", currencyCode: "EUR" },
    featuredImage: {
      url: "/templates/birthdays/birthday-inv-2.png",
      altText: "Kids Birthday",
      width: 800,
      height: 600,
    },
    currencyCode: "EUR",
    priceRange: {
      minVariantPrice: { amount: "0.75", currencyCode: "EUR" },
      maxVariantPrice: { amount: "0.75", currencyCode: "EUR" },
    },
    seo: { title: "Kids Birthday", description: "Kids birthday invite" },
    options: [],
    tags: ["birthday"],
    variants: [],
    images: [
      {
        url: "/templates/birthdays/birthday-inv-2.png",
        altText: "Kids Birthday",
        width: 800,
        height: 600,
      },
    ],
    availableForSale: true,
    minQuantity: 30,
    quantityStep: 20,
  },
  {
    id: 6,
    title: "Birthday Bash",
    handle: "birthday-bash",
    description: "Perfect for milestone birthday parties.",
    descriptionHtml: "<p>Perfect for milestone birthday parties.</p>",
    categoryId: "birthday",
    compareAtPrice: { amount: "1.00", currencyCode: "EUR" },
    featuredImage: {
      url: "/templates/birthdays/birthday-inv-1.png",
      altText: "Birthday Bash",
      width: 800,
      height: 600,
    },
    currencyCode: "EUR",
    priceRange: {
      minVariantPrice: { amount: "0.75", currencyCode: "EUR" },
      maxVariantPrice: { amount: "0.75", currencyCode: "EUR" },
    },
    seo: { title: "Birthday Bash", description: "Birthday party invite" },
    options: [],
    tags: ["birthday"],
    variants: [],
    images: [
      {
        url: "/templates/birthdays/birthday-inv-1.png",
        altText: "Birthday Bash",
        width: 800,
        height: 600,
      },
    ],
    availableForSale: true,
    minQuantity: 30,
    quantityStep: 20,
  },

  // -----------------------------
  // EVENTS (min 30, step 30)
  // -----------------------------
  {
    id: 7,
    title: "Bachelor Night",
    handle: "bachelor-night",
    description: "Bachelor party themed template.",
    descriptionHtml: "<p>Bachelor party themed template.</p>",
    categoryId: "events",
    compareAtPrice: { amount: "1.00", currencyCode: "EUR" },
    featuredImage: {
      url: "/templates/events/event-inv-1.png",
      altText: "Bachelor Night",
      width: 800,
      height: 600,
    },
    currencyCode: "EUR",
    priceRange: {
      minVariantPrice: { amount: "0.75", currencyCode: "EUR" },
      maxVariantPrice: { amount: "0.75", currencyCode: "EUR" },
    },
    seo: { title: "Bachelor Night", description: "Bachelor party invite" },
    options: [],
    tags: ["events"],
    variants: [],
    images: [
      {
        url: "/templates/events/event-inv-1.png",
        altText: "Bachelor Night",
        width: 800,
        height: 600,
      },
    ],
    availableForSale: true,
    minQuantity: 30,
    quantityStep: 30,
  },
  {
    id: 8,
    title: "Corporate Event",
    handle: "corporate-event",
    description: "Professional design for business events.",
    descriptionHtml: "<p>Professional design for business events.</p>",
    categoryId: "events",
    compareAtPrice: { amount: "1.00", currencyCode: "EUR" },
    featuredImage: {
      url: "/templates/events/event-inv-1.png",
      altText: "Corporate Event",
      width: 800,
      height: 600,
    },
    currencyCode: "EUR",
    priceRange: {
      minVariantPrice: { amount: "0.75", currencyCode: "EUR" },
      maxVariantPrice: { amount: "0.75", currencyCode: "EUR" },
    },
    seo: { title: "Corporate Event", description: "Corporate event invite" },
    options: [],
    tags: ["events"],
    variants: [],
    images: [
      {
        url: "/templates/events/event-inv-1.png",
        altText: "Corporate Event",
        width: 800,
        height: 600,
      },
    ],
    availableForSale: true,
    minQuantity: 30,
    quantityStep: 30,
  },
  {
    id: 9,
    title: "Summer Party",
    handle: "summer-party",
    description: "Vibrant summer party invitation.",
    descriptionHtml: "<p>Vibrant summer party invitation.</p>",
    categoryId: "events",
    compareAtPrice: { amount: "1.00", currencyCode: "EUR" },
    featuredImage: {
      url: "/templates/events/event-inv-1.png",
      altText: "Summer Party",
      width: 800,
      height: 600,
    },
    currencyCode: "EUR",
    priceRange: {
      minVariantPrice: { amount: "0.75", currencyCode: "EUR" },
      maxVariantPrice: { amount: "0.75", currencyCode: "EUR" },
    },
    seo: { title: "Summer Party", description: "Summer party invite" },
    options: [],
    tags: ["events"],
    variants: [],
    images: [
      {
        url: "/templates/events/event-inv-1.png",
        altText: "Summer Party",
        width: 800,
        height: 600,
      },
    ],
    availableForSale: true,
    minQuantity: 30,
    quantityStep: 30,
  },
];
