import type { Product, Collection } from "@/lib/shopify/types";

export const collections: Collection[] = [
  {
    handle: "wedding",
    title: "Pozivnice za vjenčanje",
    description: "Elegantne pozivnice za vjenčanja",
    seo: {
      title: "Pozivnice za vjenčanje",
      description: "Elegantne pozivnice za vjenčanja",
    },
    parentCategoryTree: [],
    updatedAt: new Date().toISOString(),
    path: "/categories/wedding",
  },
  {
    handle: "birthday",
    title: "Rođendanske pozivnice",
    description: "Zabavne pozivnice za rođendanske proslave",
    seo: {
      title: "Rođendanske pozivnice",
      description: "Zabavne pozivnice za rođendanske proslave",
    },
    parentCategoryTree: [],
    updatedAt: new Date().toISOString(),
    path: "/categories/birthday",
  },
  {
    handle: "events",
    title: "Pozivnice za događanja",
    description: "Pozivnice za zabave i posebne događaje",
    seo: {
      title: "Pozivnice za događanja",
      description: "Pozivnice za zabave i posebne događaje",
    },
    parentCategoryTree: [],
    updatedAt: new Date().toISOString(),
    path: "/categories/events",
  },
];

export const products: Product[] = [
  // -----------------------------
  // VJENČANJA (min 50, korak 50)
  // -----------------------------
  {
    id: 1,
    title: "Klasično vjenčanje",
    handle: "classic-wedding",
    description: "Bezvremenski i elegantan dizajn pozivnice koji odiše profinjenošću i stilom.",
    descriptionHtml: "<p>Bezvremenski i elegantan dizajn pozivnice za vjenčanje.</p>",
    categoryId: "wedding",
    compareAtPrice: { amount: "1.00", currencyCode: "EUR" },
    featuredImage: {
      url: "/templates/weddings/wedding-inv-1.png",
      altText: "Klasično vjenčanje",
      width: 800,
      height: 600,
    },
    currencyCode: "EUR",
    priceRange: {
      minVariantPrice: { amount: "0.75", currencyCode: "EUR" },
      maxVariantPrice: { amount: "0.75", currencyCode: "EUR" },
    },
    seo: { title: "Klasično vjenčanje", description: "Elegantna pozivnica za vjenčanje" },
    options: [],
    tags: ["wedding"],
    variants: [],
    images: [
      {
        url: "/templates/weddings/wedding-inv-1.png",
        altText: "Klasično vjenčanje",
        width: 800,
        height: 600,
      },
    ],
    availableForSale: true,
    minQuantity: 50,
    quantityStep: 50,
  },
  {
    id: 2,
    title: "Moderno vjenčanje",
    handle: "modern-wedding",
    description: "Minimalistički i moderan stil pozivnice.",
    descriptionHtml: "<p>Minimalistički i moderan stil pozivnice.</p>",
    categoryId: "wedding",
    compareAtPrice: { amount: "1.00", currencyCode: "EUR" },
    featuredImage: {
      url: "/templates/weddings/wedding-inv-2.png",
      altText: "Moderno vjenčanje",
      width: 800,
      height: 600,
    },
    currencyCode: "EUR",
    priceRange: {
      minVariantPrice: { amount: "0.75", currencyCode: "EUR" },
      maxVariantPrice: { amount: "0.75", currencyCode: "EUR" },
    },
    seo: { title: "Moderno vjenčanje", description: "Moderna pozivnica za vjenčanje" },
    options: [],
    tags: ["wedding"],
    variants: [],
    images: [
      {
        url: "/templates/weddings/wedding-inv-2.png",
        altText: "Moderno vjenčanje",
        width: 800,
        height: 600,
      },
    ],
    availableForSale: true,
    minQuantity: 50,
    quantityStep: 50,
  },
  {
    id: 3,
    title: "Luksuzno vjenčanje",
    handle: "luxury-wedding",
    description: "Premium dizajn s luksuznim zlatnim detaljima.",
    descriptionHtml: "<p>Premium dizajn s luksuznim zlatnim detaljima.</p>",
    categoryId: "wedding",
    compareAtPrice: { amount: "1.00", currencyCode: "EUR" },
    featuredImage: {
      url: "/templates/weddings/wedding-inv-3.png",
      altText: "Luksuzno vjenčanje",
      width: 800,
      height: 600,
    },
    currencyCode: "EUR",
    priceRange: {
      minVariantPrice: { amount: "0.75", currencyCode: "EUR" },
      maxVariantPrice: { amount: "0.75", currencyCode: "EUR" },
    },
    seo: { title: "Luksuzno vjenčanje", description: "Luksuzna pozivnica za vjenčanje" },
    options: [],
    tags: ["wedding"],
    variants: [],
    images: [
      {
        url: "/templates/weddings/wedding-inv-3.png",
        altText: "Luksuzno vjenčanje",
        width: 800,
        height: 600,
      },
    ],
    availableForSale: true,
    minQuantity: 50,
    quantityStep: 50,
  },

  // -----------------------------
  // ROĐENDANI (min 30, korak 20)
  // -----------------------------
  {
    id: 4,
    title: "Zabavni rođendan",
    handle: "fun-birthday",
    description: "Veseli i šareni dizajn savršen za rođendanske proslave.",
    descriptionHtml: "<p>Veseli i šareni dizajn savršen za rođendanske proslave.</p>",
    categoryId: "birthday",
    compareAtPrice: { amount: "1.00", currencyCode: "EUR" },
    featuredImage: {
      url: "/templates/birthdays/birthday-inv-1.png",
      altText: "Zabavni rođendan",
      width: 800,
      height: 600,
    },
    currencyCode: "EUR",
    priceRange: {
      minVariantPrice: { amount: "0.75", currencyCode: "EUR" },
      maxVariantPrice: { amount: "0.75", currencyCode: "EUR" },
    },
    seo: { title: "Zabavni rođendan", description: "Zabavna rođendanska pozivnica" },
    options: [],
    tags: ["birthday"],
    variants: [],
    images: [
      {
        url: "/templates/birthdays/birthday-inv-1.png",
        altText: "Zabavni rođendan",
        width: 800,
        height: 600,
      },
    ],
    availableForSale: true,
    minQuantity: 30,
    quantityStep: 20,
  },
  {
    id: 5,
    title: "Dječji rođendan",
    handle: "kids-birthday",
    description: "Slatka i razigrana pozivnica za dječje rođendane.",
    descriptionHtml: "<p>Slatka i razigrana pozivnica za dječje rođendane.</p>",
    categoryId: "birthday",
    compareAtPrice: { amount: "1.00", currencyCode: "EUR" },
    featuredImage: {
      url: "/templates/birthdays/birthday-inv-2.png",
      altText: "Dječji rođendan",
      width: 800,
      height: 600,
    },
    currencyCode: "EUR",
    priceRange: {
      minVariantPrice: { amount: "0.75", currencyCode: "EUR" },
      maxVariantPrice: { amount: "0.75", currencyCode: "EUR" },
    },
    seo: { title: "Dječji rođendan", description: "Pozivnica za dječji rođendan" },
    options: [],
    tags: ["birthday"],
    variants: [],
    images: [
      {
        url: "/templates/birthdays/birthday-inv-2.png",
        altText: "Dječji rođendan",
        width: 800,
        height: 600,
      },
    ],
    availableForSale: true,
    minQuantity: 30,
    quantityStep: 20,
  },
  {
    id: 6,
    title: "Rođendanska zabava",
    handle: "birthday-bash",
    description: "Savršeno za velike i posebne rođendanske proslave.",
    descriptionHtml: "<p>Savršeno za velike i posebne rođendanske proslave.</p>",
    categoryId: "birthday",
    compareAtPrice: { amount: "1.00", currencyCode: "EUR" },
    featuredImage: {
      url: "/templates/birthdays/birthday-inv-1.png",
      altText: "Rođendanska zabava",
      width: 800,
      height: 600,
    },
    currencyCode: "EUR",
    priceRange: {
      minVariantPrice: { amount: "0.75", currencyCode: "EUR" },
      maxVariantPrice: { amount: "0.75", currencyCode: "EUR" },
    },
    seo: { title: "Rođendanska zabava", description: "Pozivnica za rođendansku zabavu" },
    options: [],
    tags: ["birthday"],
    variants: [],
    images: [
      {
        url: "/templates/birthdays/birthday-inv-1.png",
        altText: "Rođendanska zabava",
        width: 800,
        height: 600,
      },
    ],
    availableForSale: true,
    minQuantity: 30,
    quantityStep: 20,
  },

  // -----------------------------
  // DOGAĐAJI (min 30, korak 30)
  // -----------------------------
  {
    id: 7,
    title: "Momačka večer",
    handle: "bachelor-night",
    description: "Zabavna i odvažna pozivnica za momačku večer.",
    descriptionHtml: "<p>Zabavna i odvažna pozivnica za momačku večer.</p>",
    categoryId: "events",
    compareAtPrice: { amount: "1.00", currencyCode: "EUR" },
    featuredImage: {
      url: "/templates/events/event-inv-1.png",
      altText: "Momačka večer",
      width: 800,
      height: 600,
    },
    currencyCode: "EUR",
    priceRange: {
      minVariantPrice: { amount: "0.75", currencyCode: "EUR" },
      maxVariantPrice: { amount: "0.75", currencyCode: "EUR" },
    },
    seo: { title: "Momačka večer", description: "Pozivnica za momačku večer" },
    options: [],
    tags: ["events"],
    variants: [],
    images: [
      {
        url: "/templates/events/event-inv-1.png",
        altText: "Momačka večer",
        width: 800,
        height: 600,
      },
    ],
    availableForSale: true,
    minQuantity: 30,
    quantityStep: 30,
  },
  {
    id: 8,
    title: "Poslovni event",
    handle: "corporate-event",
    description: "Profesionalna pozivnica za poslovna događanja.",
    descriptionHtml: "<p>Profesionalna pozivnica za poslovna događanja.</p>",
    categoryId: "events",
    compareAtPrice: { amount: "1.00", currencyCode: "EUR" },
    featuredImage: {
      url: "/templates/events/event-inv-1.png",
      altText: "Poslovni event",
      width: 800,
      height: 600,
    },
    currencyCode: "EUR",
    priceRange: {
      minVariantPrice: { amount: "0.75", currencyCode: "EUR" },
      maxVariantPrice: { amount: "0.75", currencyCode: "EUR" },
    },
    seo: { title: "Poslovni event", description: "Pozivnica za korporativni događaj" },
    options: [],
    tags: ["events"],
    variants: [],
    images: [
      {
        url: "/templates/events/event-inv-1.png",
        altText: "Poslovni event",
        width: 800,
        height: 600,
      },
    ],
    availableForSale: true,
    minQuantity: 30,
    quantityStep: 30,
  },
  {
    id: 9,
    title: "Ljetna zabava",
    handle: "summer-party",
    description: "Živopisan i veseo dizajn savršen za ljetne zabave.",
    descriptionHtml: "<p>Živopisan i veseo dizajn savršen za ljetne zabave.</p>",
    categoryId: "events",
    compareAtPrice: { amount: "1.00", currencyCode: "EUR" },
    featuredImage: {
      url: "/templates/events/event-inv-1.png",
      altText: "Ljetna zabava",
      width: 800,
      height: 600,
    },
    currencyCode: "EUR",
    priceRange: {
      minVariantPrice: { amount: "0.75", currencyCode: "EUR" },
      maxVariantPrice: { amount: "0.75", currencyCode: "EUR" },
    },
    seo: { title: "Ljetna zabava", description: "Pozivnica za ljetnu zabavu" },
    options: [],
    tags: ["events"],
    variants: [],
    images: [
      {
        url: "/templates/events/event-inv-1.png",
        altText: "Ljetna zabava",
        width: 800,
        height: 600,
      },
    ],
    availableForSale: true,
    minQuantity: 30,
    quantityStep: 30,
  },
];
